// Package hardware projects the shape graph onto Verilog.
//
// Like pkg/store projects shapes to binary on disk, this package
// projects shapes to gate configurations on an FPGA. Same structure,
// different substrate.
//
// The projection maps:
//
//	Shape.ID         -> gate index (physical position)
//	Shape.Character  -> transform_cfg (LUT truth table)
//	Shape.Structure  -> connection matrix (routing)
//	Shape.Tick       -> initial tick value
//
// Output is a Verilog top module that instantiates shape_lattice
// with the full configuration.
package hardware

import (
	"fmt"
	"hash/fnv"
	"io"
	"math"
	"sort"
	"strings"

	"github.com/ashbuilds/shape-engine/pkg/shape"
)

// Config controls the Verilog projection.
type Config struct {
	ContentWidth int // Bits per shape character (default 8).
	TickWidth    int // Bits per tick counter (default 16).
	MaxDeps      int // Max dependencies per gate (default 4).
	ModuleName   string
}

// DefaultConfig returns sensible defaults.
func DefaultConfig() Config {
	return Config{
		ContentWidth: 8,
		TickWidth:    16,
		MaxDeps:      4,
		ModuleName:   "shape_os",
	}
}

// Placement maps shape IDs to gate indices.
type Placement struct {
	Index map[shape.ID]int
	IDs   []shape.ID // Ordered by index.
	Rows  int
	Cols  int
}

// Place assigns each shape a gate index. Shapes are sorted by ID
// (which mirrors the namespace hierarchy) so that nearby shapes
// in the namespace are nearby in the lattice. This minimizes
// routing distance for dependencies.
func Place(shapes []*shape.Shape) *Placement {
	// Sort by ID for locality.
	sorted := make([]*shape.Shape, len(shapes))
	copy(sorted, shapes)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].ID < sorted[j].ID
	})

	index := make(map[shape.ID]int, len(sorted))
	ids := make([]shape.ID, len(sorted))
	for i, s := range sorted {
		index[s.ID] = i
		ids[i] = s.ID
	}

	// Compute grid dimensions: smallest square that fits.
	n := len(sorted)
	cols := int(math.Ceil(math.Sqrt(float64(n))))
	rows := int(math.Ceil(float64(n) / float64(cols)))

	return &Placement{
		Index: index,
		IDs:   ids,
		Rows:  rows,
		Cols:  cols,
	}
}

// hashContent hashes shape content to a fixed-width value for the
// transform configuration. This is the projection of arbitrary
// content onto a LUT truth table.
func hashContent(content string, width int) uint64 {
	h := fnv.New64a()
	h.Write([]byte(content))
	mask := uint64((1 << width) - 1)
	return h.Sum64() & mask
}

// Generate writes the complete Verilog top module to w.
func Generate(w io.Writer, shapes []*shape.Shape, cfg Config) error {
	if cfg.ContentWidth == 0 {
		cfg = DefaultConfig()
	}

	p := Place(shapes)
	n := len(p.IDs)

	// Build shape lookup for dep resolution.
	shapeMap := make(map[shape.ID]*shape.Shape, len(shapes))
	for _, s := range shapes {
		shapeMap[s.ID] = s
	}

	// Header.
	fmt.Fprintf(w, "// Generated by shape-lang -> Verilog projection.\n")
	fmt.Fprintf(w, "// %d shapes mapped to %dx%d lattice (%d gates).\n",
		n, p.Rows, p.Cols, p.Rows*p.Cols)
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// Shape placement (gate index -> shape ID):\n")
	for i, id := range p.IDs {
		fmt.Fprintf(w, "//   [%3d] %s\n", i, id)
	}
	fmt.Fprintf(w, "\n")

	numGates := p.Rows * p.Cols
	idxWidth := int(math.Ceil(math.Log2(float64(numGates + 1))))
	if idxWidth < 1 {
		idxWidth = 1
	}

	// Module declaration.
	fmt.Fprintf(w, "module %s (\n", cfg.ModuleName)
	fmt.Fprintf(w, "    input  wire clk,\n")
	fmt.Fprintf(w, "    input  wire rst,\n")
	fmt.Fprintf(w, "    input  wire                     ext_wave,\n")
	fmt.Fprintf(w, "    input  wire [%d:0] ext_target,\n", idxWidth-1)
	fmt.Fprintf(w, "    input  wire [%d:0] ext_data,\n", cfg.ContentWidth-1)
	fmt.Fprintf(w, "    output wire [%d:0] all_coherent,\n", numGates-1)
	fmt.Fprintf(w, "    output wire [%d:0] all_wave_out\n", numGates-1)
	fmt.Fprintf(w, ");\n\n")

	// Parameters.
	fmt.Fprintf(w, "    localparam ROWS          = %d;\n", p.Rows)
	fmt.Fprintf(w, "    localparam COLS          = %d;\n", p.Cols)
	fmt.Fprintf(w, "    localparam CONTENT_WIDTH = %d;\n", cfg.ContentWidth)
	fmt.Fprintf(w, "    localparam TICK_WIDTH    = %d;\n", cfg.TickWidth)
	fmt.Fprintf(w, "    localparam MAX_DEPS      = %d;\n", cfg.MaxDeps)
	fmt.Fprintf(w, "    localparam NUM_GATES     = %d;\n", numGates)
	fmt.Fprintf(w, "    localparam IDX_WIDTH     = %d;\n\n", idxWidth)

	// Transform configurations: one per gate.
	fmt.Fprintf(w, "    // Transform configurations (shape content -> LUT truth table).\n")
	fmt.Fprintf(w, "    wire [NUM_GATES*CONTENT_WIDTH-1:0] transform_cfgs;\n")
	for i, id := range p.IDs {
		s := shapeMap[id]
		hash := hashContent(s.Character.Content, cfg.ContentWidth)
		fmt.Fprintf(w, "    assign transform_cfgs[%d:%d] = %d'h%0*X; // %s\n",
			(i+1)*cfg.ContentWidth-1, i*cfg.ContentWidth,
			cfg.ContentWidth, cfg.ContentWidth/4, hash, id)
	}
	// Fill unused gates with zero.
	for i := n; i < numGates; i++ {
		fmt.Fprintf(w, "    assign transform_cfgs[%d:%d] = %d'h0; // unused\n",
			(i+1)*cfg.ContentWidth-1, i*cfg.ContentWidth, cfg.ContentWidth)
	}
	fmt.Fprintf(w, "\n")

	// Connection matrix: for each gate, MAX_DEPS source indices.
	fmt.Fprintf(w, "    // Connection matrix (dependency routing).\n")
	fmt.Fprintf(w, "    wire [NUM_GATES*MAX_DEPS*IDX_WIDTH-1:0] connections;\n")

	noConn := numGates // Index = NUM_GATES means "no connection".
	for i := 0; i < numGates; i++ {
		deps := make([]int, cfg.MaxDeps)
		for d := range deps {
			deps[d] = noConn
		}

		if i < n {
			id := p.IDs[i]
			s := shapeMap[id]
			// Map shape deps to gate indices.
			depIdx := 0
			for _, depID := range s.Structure.Transformation.Deps {
				if depIdx >= cfg.MaxDeps {
					break
				}
				if gi, ok := p.Index[depID]; ok {
					deps[depIdx] = gi
					depIdx++
				}
			}
			// Also map parent (implicit structure from ID hierarchy).
			if depIdx < cfg.MaxDeps {
				parts := strings.Split(string(id), ".")
				if len(parts) > 1 {
					parentID := shape.ID(strings.Join(parts[:len(parts)-1], "."))
					if gi, ok := p.Index[parentID]; ok {
						// Don't duplicate.
						found := false
						for _, d := range deps[:depIdx] {
							if d == gi {
								found = true
								break
							}
						}
						if !found {
							deps[depIdx] = gi
						}
					}
				}
			}
		}

		base := i * cfg.MaxDeps * idxWidth
		for d := 0; d < cfg.MaxDeps; d++ {
			lo := base + d*idxWidth
			hi := lo + idxWidth - 1
			comment := ""
			if i < n && deps[d] < n {
				comment = fmt.Sprintf(" // %s -> %s", p.IDs[i], p.IDs[deps[d]])
			}
			fmt.Fprintf(w, "    assign connections[%d:%d] = %d'd%d;%s\n",
				hi, lo, idxWidth, deps[d], comment)
		}
	}
	fmt.Fprintf(w, "\n")

	// Lattice wires.
	fmt.Fprintf(w, "    // Lattice outputs.\n")
	fmt.Fprintf(w, "    wire [NUM_GATES*CONTENT_WIDTH-1:0] lattice_content;\n")
	fmt.Fprintf(w, "    wire [NUM_GATES*TICK_WIDTH-1:0]    lattice_ticks;\n\n")

	// Instantiate lattice.
	fmt.Fprintf(w, "    shape_lattice #(\n")
	fmt.Fprintf(w, "        .ROWS(ROWS),\n")
	fmt.Fprintf(w, "        .COLS(COLS),\n")
	fmt.Fprintf(w, "        .CONTENT_WIDTH(CONTENT_WIDTH),\n")
	fmt.Fprintf(w, "        .TICK_WIDTH(TICK_WIDTH),\n")
	fmt.Fprintf(w, "        .MAX_DEPS(MAX_DEPS)\n")
	fmt.Fprintf(w, "    ) lattice (\n")
	fmt.Fprintf(w, "        .clk(clk),\n")
	fmt.Fprintf(w, "        .rst(rst),\n")
	fmt.Fprintf(w, "        .ext_wave(ext_wave),\n")
	fmt.Fprintf(w, "        .ext_target(ext_target),\n")
	fmt.Fprintf(w, "        .ext_data(ext_data),\n")
	fmt.Fprintf(w, "        .transform_cfgs(transform_cfgs),\n")
	fmt.Fprintf(w, "        .connections(connections),\n")
	fmt.Fprintf(w, "        .all_content(lattice_content),\n")
	fmt.Fprintf(w, "        .all_ticks(lattice_ticks),\n")
	fmt.Fprintf(w, "        .all_coherent(all_coherent),\n")
	fmt.Fprintf(w, "        .all_wave_out(all_wave_out)\n")
	fmt.Fprintf(w, "    );\n\n")

	fmt.Fprintf(w, "endmodule\n")

	return nil
}
