shape os.shell.cmd.help {
  type: exec
  layer: 4
  """
print("Shape Shell — everything is a shape")
print("")
print("Navigation:")
print("  pwd                  Print current prefix")
print("  cd <prefix>          Change prefix (.. to go up, / for root)")
print("  ls [prefix]          List shapes at prefix")
print("  tree [prefix]        Recursive tree view")
print("  find <pattern>       Search shapes by ID")
print("")
print("Shape Operations:")
print("  cat <id>             Show shape content and dimensions")
print("  info <id>            Full shape dump")
print("  mkdir <id>           Create empty shape")
print("  rm <id>              Delete shape (if no dependents)")
print("  cp <src> <dst>       Clone shape")
print("  mv <src> <dst>       Move shape")
print("  echo text > <id>     Set shape content")
print("  edit <id> <content>  Edit shape content, propagate wave")
print("  grep <pattern>       Search shape content")
print("  open <id>            Full shape viewer with ancestry and stats")
print("  ancestry <id>        Show derivation chain to axiom")
print("")
print("Graph Operations:")
print("  deps <id>            Show dependencies")
print("  dependents <id>      Show reverse dependencies")
print("  wave <id>            Show propagation path")
print("  validate             Run coherence check")
print("  status               Engine status")
print("  tick                 Global tick counter")
print("")
print("Language:")
print("  run <source|id>      Execute shape-lang")
print("  <name>               Run executable shape (type: exec)")
print("  <name>               Display content shape (default)")
print("")
print("Identity & Economy:")
print("  whoami               Show current session actor")
print("  login <user-id>      Set session actor, initialize tick balance")
print("  account              Tick balance, economy config, audit summary")
print("  audit [user-id]      Detailed moment-by-moment audit trail")
print("")
print("Shell:")
print("  env / export K=V     Environment variables")
print("  history / alias k=v  History and aliases")
print("  config [key] [val]   OS configuration (e.g. config headers off)")
print("  clear / help         Clear screen / this message")
print("")
print("Testing:")
print("  test [suite]         Run structural tests (law, shape, engine, lang, shell, os)")
print("  test -v [suite]      Verbose output")
print("  test --list          List all test shapes")
print("  test --history       Show test execution history")
print("  test --coverage      Structural coverage report")
print("  test --moments [N]   Show last N moments across all layers")
print("  test --branch        Show trace branch state")
print("LLM Agent:")
print("  ask <question>       Ask the LLM agent to construct shapes")
print("  ask status           Show current/last agent task")
print("  ask steps <id>       Show steps for a task")
print("")
print("Agents & Events:")
print("  agent                manage shape agents (create, pause, resume, remove)")
print("  event                declarative event hooks on shape changes")
print("  notify               notification system (send, list, clear)")
print("  clip                 clipboard operations")
print("")
print("Piping: ls | grep edit | cat")
print("All commands are shapes under os.shell.cmd.* — edit them to change the OS.")
"""
}
