shape hardware.compile : hardware {
  type: exec
  layer: 3
  desc: "Project shapes to Verilog"
  """
// hardware.compile -- project shape graph onto Verilog gate lattice.
//
// Usage: run hardware.compile
//   or from shell: compile-hw [output.v]
//
// The projection:
//   Shape.ID        -> gate index (sorted by ID for locality)
//   Shape.Character -> transform_cfg (content hash -> LUT truth table)
//   Shape.Structure -> connection matrix (deps -> wave_in routing)
//   Shape.Tick      -> initial tick value
//
// Output: Verilog module that instantiates shape_lattice with full config.

let all = sort_list(shapes_under(""))
let n = len(all)
let cols = ceil(pow(n, 0.5))
let rows = ceil(n / cols)
let num_gates = rows * cols
let cw = 8
let tw = 16
let max_deps = 4

// Header
print("// Generated by hardware.compile: shape-lang -> Verilog projection.")
print("// " + n + " shapes mapped to " + rows + "x" + cols + " lattice (" + num_gates + " gates).")
print("//")
print("// Shape placement (gate index -> shape ID):")
let idx = 0
for id in all {
  print("//   [" + pad_left(to_string(idx), 3) + "] " + id)
  set idx = idx + 1
}
print("")

// Module declaration
let idx_width = ceil(pow(num_gates + 1, 0.5))
if idx_width < 1 {
  set idx_width = 1
}
// Compute log2 ceiling for index width
set idx_width = 1
let temp = num_gates
while temp > 1 {
  set idx_width = idx_width + 1
  set temp = ceil(temp / 2)
}

print("module shape_os (")
print("    input  wire clk,")
print("    input  wire rst,")
print("    input  wire                     ext_wave,")
print("    input  wire [" + (idx_width - 1) + ":0] ext_target,")
print("    input  wire [" + (cw - 1) + ":0] ext_data,")
print("    output wire [" + (num_gates - 1) + ":0] all_coherent,")
print("    output wire [" + (num_gates - 1) + ":0] all_wave_out")
print(");")
print("")

// Parameters
print("    localparam ROWS          = " + rows + ";")
print("    localparam COLS          = " + cols + ";")
print("    localparam CONTENT_WIDTH = " + cw + ";")
print("    localparam TICK_WIDTH    = " + tw + ";")
print("    localparam MAX_DEPS      = " + max_deps + ";")
print("    localparam NUM_GATES     = " + num_gates + ";")
print("    localparam IDX_WIDTH     = " + idx_width + ";")
print("")

// Transform configs
print("    wire [NUM_GATES*CONTENT_WIDTH-1:0] transform_cfgs;")
set idx = 0
for id in all {
  let c = content(id)
  // Hash content to cw bits using shape_tick as proxy
  let hash = mod(tick(id) * 31 + len(c) * 7, 256)
  let hi = (idx + 1) * cw - 1
  let lo = idx * cw
  print("    assign transform_cfgs[" + hi + ":" + lo + "] = " + cw + "'h" + hash + "; // " + id)
  set idx = idx + 1
}
// Fill unused gates
while idx < num_gates {
  let hi = (idx + 1) * cw - 1
  let lo = idx * cw
  print("    assign transform_cfgs[" + hi + ":" + lo + "] = " + cw + "'h0; // unused")
  set idx = idx + 1
}
print("")

// Connection matrix
print("    wire [NUM_GATES*MAX_DEPS*IDX_WIDTH-1:0] connections;")

// Build index lookup
let gate_map = map_new()
set idx = 0
for id in all {
  set gate_map = map_set(gate_map, id, idx)
  set idx = idx + 1
}

set idx = 0
for id in all {
  let dp = deps(id)
  let dep_indices = []
  for dep in dp {
    if map_has(gate_map, dep) {
      set dep_indices = append(dep_indices, map_get(gate_map, dep))
    }
  }
  // Also add parent as implicit dep
  let p = parent(id)
  if p != "" {
    if map_has(gate_map, p) {
      let pi = map_get(gate_map, p)
      if !(pi in dep_indices) {
        set dep_indices = append(dep_indices, pi)
      }
    }
  }
  // Pad to max_deps with num_gates (no connection)
  while len(dep_indices) < max_deps {
    set dep_indices = append(dep_indices, num_gates)
  }
  for d in range(max_deps) {
    let lo = (idx * max_deps + d) * idx_width
    let hi = lo + idx_width - 1
    let src = index(dep_indices, d)
    let comment = ""
    if src < n {
      set comment = " // " + id + " -> " + index(all, src)
    }
    print("    assign connections[" + hi + ":" + lo + "] = " + idx_width + "'d" + src + ";" + comment)
  }
  set idx = idx + 1
}
// Fill unused gate connections
while idx < num_gates {
  for d in range(max_deps) {
    let lo = (idx * max_deps + d) * idx_width
    let hi = lo + idx_width - 1
    print("    assign connections[" + hi + ":" + lo + "] = " + idx_width + "'d" + num_gates + ";")
  }
  set idx = idx + 1
}
print("")

// Lattice wires and instantiation
print("    wire [NUM_GATES*CONTENT_WIDTH-1:0] lattice_content;")
print("    wire [NUM_GATES*TICK_WIDTH-1:0]    lattice_ticks;")
print("")
print("    shape_lattice #(")
print("        .ROWS(ROWS),")
print("        .COLS(COLS),")
print("        .CONTENT_WIDTH(CONTENT_WIDTH),")
print("        .TICK_WIDTH(TICK_WIDTH),")
print("        .MAX_DEPS(MAX_DEPS)")
print("    ) lattice (")
print("        .clk(clk),")
print("        .rst(rst),")
print("        .ext_wave(ext_wave),")
print("        .ext_target(ext_target),")
print("        .ext_data(ext_data),")
print("        .transform_cfgs(transform_cfgs),")
print("        .connections(connections),")
print("        .all_content(lattice_content),")
print("        .all_ticks(lattice_ticks),")
print("        .all_coherent(all_coherent),")
print("        .all_wave_out(all_wave_out)")
print("    );")
print("")
print("endmodule")
"""
}
